### ISSUE TITLE
Feature request: Render TT from string

### ISSUE THREAD

**Issue by scmorrison** [supernovus/template6#20]
I am not sure if this is planned, or maybe already implemented and I am just missing it, but it would be useful to do something like this:

```perl6
my $tt = q:to/END/;
    <h1>Hello, [% name %]!</h1>
    END

$t6.stash-template: 'helloworld', $tt;
say $t6.process: 'helloworld', :name<World>;
```

Thanks,
Sam

**Comment by supernovus** [comment]
It currently doesn't support this, but it has been planned for eons by adding a new Provider class.
I haven't been actively working on any of my Perl 6 libraries in a few years, but I'll look at adding a String provider class and make it available by default like the File provider class is now. I probably won't be able to get to it today as $DayJob keeps me pretty busy, but I will add something this week, cheers!

**Comment by scmorrison** [comment]
Thanks for the response and for taking the time to work on this. I feel your $DayJob pain. Looking forward to testing.
